version: "3.8"

services:
  blue:
    build:
      dockerfile: ./api.dockerfile
      context: .
    container_name: blue-api
    networks:
      - reverse-proxy-network
    environment:
      - COLOR=blue

  red:
    build:
      dockerfile: ./api.dockerfile
      context: .
    container_name: red-api
    networks:
      - reverse-proxy-network
    environment:
      - COLOR=red

  reverse-proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - reverse-proxy-network
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    depends_on:
      - red
      - blue

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
